### ISSUE TITLE
Let's pick a better name!

### ISSUE THREAD

**Issue by itSeez** [PaulMcInnis/JobPy#12]
| option | notes |
|:-|:-|
| `workmate` or `jobmate` | to long? |
| `slacker` or `slack` | my favourite but portrays the opposite, ironic? |
| `workaholic` | accurate but maybe not the best, to long? |
| `opus` or `operis` | both mean work in Latin |

Let me know what you guys think, and maybe propose your own suggestions :)

**Comment by studentbrad** [comment]
My favorite is slacker.
Here are some auto-generated ones.
| option | notes |
|---|---|
| jobfunnel | I know Paul liked this one. |
| joboggan | I thought this one was just funny. |
| jobanion | I say this one like Joe Banion. |
| jobuntu | sounds like ubuntu ❤️. |

Apparently the name generator really likes compound words beginning in "job".
I'm not super serious about these I just laughed when I read them.

**Comment by itSeez** [comment]
I really like `slacker`, although `slack` is definitely out the window, and I only realised that after making the issue lol. `jobfunnel` is a good one too :)

**Comment by PaulMcInnis** [comment]
Job funnel works, I like it even though it’s kinda silly 💯

Slacker is cool, tho slack is suuuper closely named - kinda ruins it for me tbh. 

Opus I like, very dignified, probably better than job funnel. 

Both of those get my vote :)

Here are some of my additional suggestions: 

- Venatus (latin for hunt)
- Job Stream
- Career Invicta (latin for automatic)

**Comment by itSeez** [comment]
We can name the project `JobFunnel` and, for short, we could use `funnel` for the executable :)

**Comment by studentbrad** [comment]
I vote on `opus` and `jobfunnel` I think those are the ones that idk just sound natural.
`operis` however is more lengthy than `opus` which I think may be a little too short to be a title.
`operis` also is singular meaning work of one individual which is kind of cool because this is very much software for one individual.

**Comment by studentbrad** [comment]
If we name it jobfunnel someone has to make a sweet cartoon graphic of someone funneling jobs 😆

**Comment by PaulMcInnis** [comment]
Soooooo I hereby rename this project:


🥁🥁🥁

‘Jobfunnel’

🥳

Now someone make us an infographic
