### ISSUE TITLE
pickles are overwritten

### ISSUE THREAD

**Issue by PaulMcInnis** [PaulMcInnis/JobPy#6]
Seems like only data from the last call in run.py will ever make it into the master list CSV.

addressing this in branch: https://github.com/PaulMcInnis/JobPy/tree/fix_job_providers

**Comment by alarconj** [comment]
you guys broke JobPy... lame
lol, I'ma write a setup script

**Comment by studentbrad** [comment]
@alarconj I believe I broke JobPy.  But yes, we do need a setup script.

**Comment by alarconj** [comment]
Hey, you're back! Welcome :)

**Comment by PaulMcInnis** [comment]
okay, never mind, I don't know what I did wrong when I tried this out, seems to work fine!

Gonna improve the handling of jobpy_obj in a different branch `make_jobpy_base_class`
